### ISSUE TITLE
Stepping out of function, expected control on next line

### ISSUE THREAD

**Issue by factormystic** [rubyide/vscode-ruby#11]
### Your environment
- `vscode-ruby` version: 0.3.1
- System: Windows 10 x64, VS Code 0.10.11
- Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

I have the following, `ruby-debug-basex19` is maybe a typo or something? It doesn't seem to be a published gem.

```
*** LOCAL GEMS ***

ap (0.1.1)
bigdecimal (1.2.6)
debase (0.2.1)
debase-ruby_core_source (0.8.4)
httparty (0.13.7)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
multi_xml (0.5.5)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
ruby-debug-ide (0.4.32)
test-unit (3.0.8)
```
### Expected behavior

For this script, with a breakpoint on line 2, I expect that step out (`shift-f11`) would put move forward the current line to line 6. Basically, you can see the expected behavior if you also put a breakpoint on line 6, and step out of line 2.

```
def hello what
    "hello #{what}" # breakpoint here, then shift-f11
end

pp hello("world")
pp "whatever" # expected control to move here
```
### Actual behavior

Script prints both lines of output and exits
### Steps to reproduce the problem

With the ruby 2 setup from the readme, paste this script in, put in the breakpoint on line 2, start debugging, hit shift f11, observe.

**Comment by HookyQR** [comment]
Unfortunately debase (as the backend debugger) doesn't provide a function for this. The `finish` function (which is the only `step out` like command) will effectively return you out of the current ___Object___ not the current ___method___. As such, when you push the step out button in the mainline of the program you are stepping out of the main ___Object___ (which is where a file 'global' method is defined).

I agree that this is not what you would expect, I was frustrated with it myself, but unfortunately, that's what we've got.

I am currently looking into using the standard ruby debug module instead of debase. It is reportedly slower, by may offer some improved user interaction within the editor, which I think should be a focus for an IDE debugger. If you were after speed, you could switch to debase on the command line.

**Comment by rebornix** [comment]
:+1: @HookyQR . 

@factormystic Currently we are limited to `debase`, which is also the gem package used by RubyMine. So if you debug this piece of code in RubyMine and step out after the breakpoint is hit, you'll run into the same situation as you do here. I'm not saying it's the correct behavior, but before we switch our ruby-side infrastructure, we are on the same boat as RubyMine.

**Comment by Dashue** [comment]
Bump? Debugging is the biggest pain point I'm hitting

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
