### ISSUE TITLE
rubocop 0.48.1 not working (calling rubocop with '-s' option)

### ISSUE THREAD

**Issue by neovatar** [rubyide/vscode-ruby#136]
### Your environment

- `vscode-ruby` version: 0.10.4 + 0.11.0 (master)
- Ruby version: 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
- VS Code version: 1.11.1
- Operating System: Ubuntu 16.04.2 LTS
- Hardware (optional): x86_64
- Rubocop version: 0.48.1

I installed `ruby`, `ruby-debug-ide`, `ruby-debug-basex19` and `rubocop`.

### Expected behavior
- configure vscode-ruby to use rubocop
- save a ruby file with an error
- vscode-ruby runs rubocop and reports a problem

### Actual behavior
- configure vscode-ruby to use rubocop
- save a ruby file with an error
- no error is reported

### Steps to reproduce the problem
- configure vscode-ruby to use rubocop with:
```
    "ruby.lint": {
        "rubocop": true
    }
```
- save a ruby file with an error e.g.:
```
def hello
  puts "hello"
```
- no error is reported

I uninstalled vscode-ruby, cloned vscode-ruby master from github and did run it in debugging mode via vscode.

I got the following error:
```
Linter error: rubocop SyntaxError: Unexpected end of JSON input
    at RuboCop.processResult (/home/tom/Data/projects/vscode-ruby/lint/lib/linters/RuboCop.js:21:22)
    at ChildProcess.global._exeLinter.spawned.on.e (/home/tom/Data/projects/vscode-ruby/lint/lib/linter.js:76:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.global.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
Once I removed the "-s" parameter from the rubocop call, the JSON error was gone and the error in my ruby file got reported correctly on save. With "-s" rubocop expects data from STDIN and does not accept a filename of a file to parse. Maybe this is the origin of the JSON input error?

**Comment by mmahalwy** [comment]
Any fix for this?

**Comment by gerrywastaken** [comment]
@neovatar @mmahalwy There seems like it was an intentional change and -s does support a filename argument:

see: 
https://github.com/rubyide/vscode-ruby/commit/ae1f03d1d328fcb19bf03105082843e8e773cbcd
and:
https://github.com/bbatsov/rubocop/pull/4226#issuecomment-291876130

I suspect the author of VS code is only testing against the latest version of Rubocop and so upgrading will probably help you out. Things are working for me with version 0.49.1 of Rubocop. Also make sure that the you are loading vscode with the correct environment as it may be picking up on the wrong rubocop if you have more than one version installed on your system.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
