### ISSUE TITLE
warning: parser/current is loading parser/ruby22, which recognizes

### ISSUE THREAD

**Issue by jcreamer898** [rubyide/vscode-ruby#139]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.2.0p
- VS Code version: 1.11.2
- Operating System: macOS 10.12.2
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Everything "works" ok, but...

### Actual behavior
I get this warning every so often whenever I edit a Ruby file...

![](http://d.pr/i/k7FB+)

Any ideas on what I may have wrong here? I tried to gem install rubocop and parser to get newer versions locally, but nothing seems to stop that warning from popping up.

**Comment by kevinleclair1** [comment]
I've looked into this a little bit. It happens to me as well when you use certain versions of Ruby.

<img width="705" alt="screen shot 2017-07-01 at 7 03 55 am" src="https://user-images.githubusercontent.com/10081438/27761529-82fd70c4-5e2b-11e7-8dee-c9b5f40b17b5.png">

Seems like it happens when you run the rubocop command, but it doesn't stop the execution of the program. It's not really an error I suppose, just a warning issued by the `parser` gem. Is there anyway that we could suppress this warning, or maybe show it in the VSCode console instead of the notification bar?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
