### ISSUE TITLE
Autocompletion doesn't work when require file

### ISSUE THREAD

**Issue by Jakitto** [rubyide/vscode-ruby#147]
### Environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.4.0 / 2.3.3
- VS Code version: 1.12.1
- Operating System: macOS Sierra 10.12.2
- Hardware (optional): MacBook Pro 2016 late / Mac Mini

### Expected behavior
My project has two file:
-  #my_class.rb
- test.rb

In `my_class.rb`, I wrote a simple bare bone MyClass for demo.

In test.rb, I wrote `require_relative 'my_class'`, which can require MyClass.

And I expected that then I'll use this class.

### Actual behavior
Code autocompletion behave strange, having no autocompletion but I feel something fall into error.

### Steps to reproduce the problem
I open DevTool so that I can see those:

`runtime_data_with_class': -:4:in `require_relative': cannot infer basepath (LoadError) (Rcodetools::ProcessParticularLine::NewCodeError)
	from -:4:in `<main>'
	from /Users/***/.rvm/gems/ruby-2.4.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:287:in `candidates_with_class'
	from /Users/***/.rvm/gems/ruby-2.4.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:295:in `candidates'
	from /Users/***/.rvm/gems/ruby-2.4.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:313:in `completion_code'
	from /Users/***/.rvm/gems/ruby-2.4.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:206:in `run'
	from /Users/***/.rvm/gems/ruby-2.4.0/gems/rcodetools-0.8.5.0/bin/rct-complete:45:in `<top (required)>'
	from /Users/***/.rvm/gems/ruby-2.4.0/bin/rct-complete:23:in `load'
	from /Users/***/.rvm/gems/ruby-2.4.0/bin/rct-complete:23:in `<main>'
	from /Users/***/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/***/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

![qq20170505-163649](https://cloud.githubusercontent.com/assets/18480287/25738697/1f7c986e-31b1-11e7-9908-ea03388267b2.png)

![qq20170505-163714](https://cloud.githubusercontent.com/assets/18480287/25738704/2c1b0704-31b1-11e7-87b4-66a19aaf82c2.png)

**Comment by Kanatatsuki** [comment]
same problem here, 
and the bug seems to be: 

/Users/XXXXXX/.rvm/gems/ruby-2.4.1/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:166:in `runtime_data_with_class': -:10: syntax error, unexpected ')' (Rcodetools::ProcessParticularLine::NewCodeError)
| x.to_s}.grep(/^\[1,2,3\]/e/);_xmp_1502777639_54194_535858_
^
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:287:in `candidates_with_class'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:295:in `candidates'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:313:in `completion_code'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:206:in `run'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/gems/rcodetools-0.8.5.0/bin/rct-complete:45:in `<top (required)>'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/bin/rct-complete:23:in `load'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/bin/rct-complete:23:in `<main>'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
from /Users/XXXXXX/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jeffbax** [comment]
Yup, that is what I see as well

Using
- macOS 10.12.6
- vscode 1.13.1
- vscode-ruby 0.14.0
- ruby 2.4
- rct-complete 0.8.5
- ruby-debug-ide-0.6.0
- debase-0.2.2.beta10

With fully qualified the path to the rbenv shim `rct-complete` and configured the `ruby.locate` user settings.

One of the other things I ran into getting to this other error point was surprise that the extensions didn't seem to respect the local `rbenv` -- and it was always defaulting to global (and one couldn't make it a workspace setting to point to a different one, it had to be a user setting)

I'm pretty new to Ruby for work, so trying a bunch of things to get to where I was with VSCode + Python... but a lot to learn yet in regards to trying to help fix this I think.

**Comment by castwide** [comment]
https://github.com/rubyide/vscode-ruby/pull/248 should resolve this issue.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
