### ISSUE TITLE
Unable to set ERB breakpoint for debugging

### ISSUE THREAD

**Issue by movilla1** [rubyide/vscode-ruby#211]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.2.4
- VS Code version: 1.17
- Operating System: Linux Ubuntu 17.04
- Hardware (optional): HP Laptop 17y-015cy

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Set breakpoint on erb file and debug code

### Actual behavior
Impossible to set a breakpoint and debug, the file name is something.html.erb and apparently the extension thinks it's html, I've not found any way to override this on settings

### Steps to reproduce the problem
Just create a file named something.html.erb and try setting up a breakpoint...

**Comment by justin-parmar** [comment]
+1

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by rockorequin** [comment]
This is definitely still an issue.

**Comment by rockorequin** [comment]
An even better workaround for this bug is to install the ERB Formatter/Beautify extension (https://marketplace.visualstudio.com/items?itemName=aliariff.vscode-erb-beautify). 

You need the htmlbeautifier gem installed, and if your file is called .html.erb you probably need to change it to be associated as an ERB file (CTRL-SHIFT-P while the file is open, select 'Change Language Mode', and set the file association to 'erb'; or the marketplace link has an option to configure this in your setup).

With all that done, you get html formatting in ERB files and you can also set breakpoints for Ruby.
