### ISSUE TITLE
Cannot make Linting work with Rubocop

### ISSUE THREAD

**Issue by damienlethiec** [rubyide/vscode-ruby#229]
### Your environment

- `vscode-ruby` version:  0.15.0
- Ruby version: 2.4.1
- VS Code version: 1.18.1
- Operating System: Mac OS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

Rubocop linting shows the errors in my files (same errors than when running with the command line)

### Actual behavior

There is not linting at all in my VSCode editor

### Steps to reproduce the problem

Add the following config to your settings (I tried others but nothing works):

```
  "ruby.lint": {
    "rubocop": {
      "lint": true,
      "rails": true
    }
  },
```

Trigger a Rubocop error (for example: wrong order of gems in gemfile). Nothing happens in VSCode but `rubocop` in the command line find the error.

I do not seem to have any error so I do not know how I can give more info. Please let me know if I can be more useful.

Thank you

**Comment by stevebutler2210** [comment]
Was this ever resolved? I'm experiencing the exact same issues myself, but on VS Code 1.19.2 and Ruby 2.5.0

**Comment by avandecreme** [comment]
It is actually working on 0.15 for me but does not on 0.17

**Comment by avandecreme** [comment]
rubocop is in my Gemfile.

```
$ which rubocop
~/.rbenv/shims/rubocop
```

I reverted back to 0.15 for now

**Comment by rpellerin** [comment]
Any updates on this? I'm affected too.

**Comment by wingrunr21** [comment]
I've been out of town for the past week or so and haven't been able to look. I'm also seeing the same issue.

**Comment by joseph0x01** [comment]
I am having the same issue with ruby v2.3.5 with RVM and the same setting. Tried to toggle  "Developer Tools", showing 
```
[Extension Host] Rubocop not installed
```

But the gem is actually installed. I open VSCode from the shell that switched to ruby 2.3.5 with RVM.

**Comment by gurgeous** [comment]
I think this is another part of the docs that could use a refresh. This kind of error is very common. It turns out that getting VS Code and rvm/rbenv/chruby to play nicely together is a non-trivial task.

Can you try investigating/installing rubocop from within VS Code's Integrated Terminal? (View > Integrated Terminal). Try `ruby -v`, `gem env gemdir`, `gem list | grep rubocop`, `which rubocop` and then `rubocop -v`.

I have a theory that this might be the easiest way to diagnose and fix gem dependency issues. Personally I have a simple rbenv setup and I'm curious how things look with rvm + VS Code.

**Comment by joseph0x01** [comment]
Many thanks. Below are the outputs from Integrated Terminal

```
$ ruby -v
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin16]
```

```
$ gem env gemdir
/Users/joseph/.rvm/gems/ruby-2.3.5
```

```
$ gem list | grep rubocop
rubocop (0.49.1)
rubocop-checkstyle_formatter (0.4.0)
rubocop-rspec (1.15.1)
```

```
$ which rubocop
/Users/joseph/.rvm/gems/ruby-2.3.5/bin/rubocop
```

```
$ rubocop -v
0.49.1
```

From Visual Studio Code Developer Tools

```
[Extension Host] Solargraph extension activated.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Rubocop not installed
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1325   ERR write EPIPE: Error: write EPIPE
	at exports._errnoException (util.js:1050:11)
	at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] The Solargraph gem is not available.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1325   ERR write EPIPE: Error: write EPIPE
	at exports._errnoException (util.js:1050:11)
	at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
log.ts:171   ERR write EPIPE: Error: write EPIPE
	at exports._errnoException (util.js:1050:11)
	at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
```

**Comment by gurgeous** [comment]
Thanks for taking the time to put that together.

Hm, that's strange. I would expect it to work if VS Code can run rubocop in the terminal. I added a new set of error messages to the rubocop activation code, but we haven't released that version of vscode-ruby yet. With 0.17.0 all you get is `Rubocop not installed`, unfortunately. The unreleased version is more verbose - https://github.com/rubyide/vscode-ruby/pull/297/files.

These kinds of errors are common. That's why I want to add more error messages and improve the docs. We appreciate your patience.

You can wait for the next release to get more debug info (which could take a few days), or if you are feeling ambitious you can try debugging the extension locally. See https://github.com/rubyide/vscode-ruby#contributing. Beware, though - it's easy to get bogged down with install/config issues if you're just dipping your toe into development. Especially if you don't know npm/js/etc. :)

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by rpellerin** [comment]
Had the same issue as you @scottohara. It's a normal behavior. When you open up a new terminal, the environment variable `$PATH` gets updated with the path to your local version of Ruby loaded through `rvm`, as well as the path to your gems.
On the other hand, when you open VS code from outside a terminal, the `$PATH` variable does no contain paths to local Ruby and gems therefore VS code falls back to your system Ruby and system-installed gems, which obviously does not point to Rubocop, which I assume was installed with `bundle`.
The proper way to launch VS code is from a termimal. This way, everything loads fine since `$PATH` points to your local Ruby and gems (including Rubocop).
Let me know if something isn't clear. Hope this helps too.

**Comment by wingrunr21** [comment]
Yep. There's a bit of code [here in the extension](https://github.com/rubyide/vscode-ruby/blob/master/src/utils.ts#L24) that attempts to rectify this problem but I'm not sure how well it works.

For instance, I'm a `chruby` user. In order for projects to pick up `.ruby-version` files I need the autoswitch functionality sourced into the shell environment. If I don't start VSCode from the command line, I inevitably get the wrong version within VSCode.

Proper support for `rvm`, `chruby`, and `rbenv` is on my list to look into.

**Comment by vnbrs** [comment]
`rbenv rehash` worked for me!!!

**Comment by stylergergely** [comment]
I am sorry but I wouldn't call this normal behavior. While I understand that `rvm` and co are using the `PATH` variable to configure the version of ruby to use, even opening VScode from the terminal doesn't solve the issue since in my case no matter what the plugin is still using the system version of ruby in the default configuration when I want to run rspec for example (OS X + zsh in my case). There is nothing normal about that. What would be normal though if I could simply control the used ruby version from the launch.json which is not the case.

Other languages (node, python, etc) could solve this problem somehow, so I suspect this is not inherently unsolvable.

**Comment by wingrunr21** [comment]
Please open a new issue or comment on the applicable open issue. This issue is out of date given version manager support shipped in the language server support.

There is an outstanding bug related to environment detection (#470) which I haven’t been able to nail down yet.

Also, as you seem rather confident that this is an easy problem to solve across four different version managers plus bundler plus global installs independent of how VSCode is launched, please open a PR with a fix.

**Comment by gurgeous** [comment]
@wingrunr21 is right - this is hard, unfortunately. Too many configurations and too few people to painstakingly recreate and debug the myriad problems with PATH and ENV.

I do have a brute force workaround to suggest - replace the rubocop executable with a bash script of your own devising. Then you can configure your PATH and ENV in a way that works on your system before launching rubocop. This technique is used to great effect by https://github.com/fohte/rubocop-daemon.

If you decide to go this route, feel free to swing back and share your findings. Ideally with a link to your replacement script!
