### ISSUE TITLE
Bad syntax highlighting of string literals with % notation

### ISSUE THREAD

**Issue by giorgian** [rubyide/vscode-ruby#24]
### Your environment

- `vscode-ruby` version: 0.3.4
- Ruby version: 2.0.0p645? (I didn't configure the ruby interpreter to use for `vscode-ruby`, is it taking the system installed one?
- VS Code version: 1.1.1
- Operating System: OS X 10.11.3
- Hardware (optional): MacBook Pro (Retina, Mid 2012)

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

It should show syntax highlighting correctly for string literals with % notation

### Actual behavior

It doesn't recognise at all the syntax `%q(...)` or `%w(...)`; it wrongly assumes that the string will terminate at the first `}`, with `%Q(})` and `%r(})` (this one is actually a literal regex, but anyway).

### Steps to reproduce the problem

Just type the following valid ruby code:

    a = %Q({}z')
    b = 4

This should highlight the string `{}z'`. 
It will instead highlight two strings, `%Q({}` and `')` till the next `'`.

    a = %q(33)

Here, it should highlight the string `%q(33)`; instead, it doesn't recognise `%q` as a prefix for string literals.

**Comment by HookyQR** [comment]
@rebornix, @giorgian. v0.3.4 doesn't have the syntax highlighting included as part of this package. My Ruby extension has syntax highlighting in it, but it does not provide the highlighting you're discussing here. I've monkey patched the highlighting in this repo (from the syntaxes/ruby.tmLanguage file) and the matching works fine. As soon as @rebornix publishes a new version, your problems will be solved.

**Comment by giorgian** [comment]
@HookyQR thank you for the fix, but I don't understand: do you mean that I submitted the issue to the wrong repo?  Where does the syntax highlighting I'm experiencing come from?

**Comment by rebornix** [comment]
@giorgian 0.4.0 is out, give it a try. Let me know if it still happens.

If you install no ruby related extension, you will get syntax highlighting from vscode by default.

**Comment by HookyQR** [comment]
@rebornix the syntax matcher you've brought in works as required.

@giorgian right repo, just too quick, as @rebornix says above.

**Comment by giorgian** [comment]
@rebornix thank you for the explanation and for the fix. 

Here's the result of my tests so far:

* the only kinds of % notation not managed seem to be `%i` and `%I` (I didn't remember those, and had never used them myself, I had to check the full list [here](https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Literals#The_.25_Notation).

* there's syntax highlight for `%S`, which doesn't exist. I don't think it may every be a major problem; here's the only kind of snippet I was able to come up with that may present an ambiguity, but if someone actually uses code like this, they have worse problems than syntax highlighting:

```
def S(n)
  n * 3
end

def a(n = 300)
  n * 2
end

c = a%S(42)
```
* I tried hard, but wasn't able to break syntax highlight for all other kinds of % notation.

**Comment by rebornix** [comment]
@giorgian thanks for your kind input :+1: . Most of VS Code's tokenization ability comes from Textmate language file (plist or tmlanguage), which is based on regular expressions. I'm digging into the mechanism behind it and try to debug this kind of regex, will let you know if there is any progress.

**Comment by HookyQR** [comment]
@rebornix I can do the %i and %s additions after work today if you've already got some work in the pipes for the extension. I'm confident with the structure of the syntax files.

**Comment by rebornix** [comment]
@HookyQR go ahead! I'll write an email to you to share my personal update.

**Comment by HookyQR** [comment]
@giorgian, @rebornix: I've incorporated the `%i` and `%I`, and dropped the `%S` matchers. Although the highlighting defines `%I{abc #{abc} def}` as having the variable `abc` embedded, it doesn't show up because the constant (which is used for symbol highlighting) style definition overrides the variable style definition.

There are a couple of way this can be highlighted that may be valid:
1. (shown) consider `%I{}` as a method and highlight as per method names, highlighting the internals as symbols. (this would not show interpolations correctly)
2. (shown) consider `%I{}` as a method and highlight as per method names, highlighting the internals as a string.
3. (not shown) consider `%I{}` as the 'constant' part and highlight the internals as a string.
4. (shown) consider the whole thing to be a 'constant' definition.

![image](https://cloud.githubusercontent.com/assets/14353068/15355105/08dda106-1d45-11e6-8fad-3a9408f7f287.png)

%i will be formatted the same, but won't allow (show) interpolation.

If we go with the 'is a method' style, we could do the same with the similar shortcuts as well.

Opinions?

**Comment by HookyQR** [comment]
I'm taking the oportunity to simplify the file. There are a bunch of `beginCapture` and `endCaptures` that can be pulled together. The file is parsed when a (at least the first) ruby file is opened, and it's (the amended version) currently 3700 lines long.

**Comment by HookyQR** [comment]
@giorgian I've used the symbol highlight colour for both the %I and %i versions. %S is removed. Have a look at the latest version (0.5.*)
