### ISSUE TITLE
Can't get rake auto-detection to work

### ISSUE THREAD

**Issue by tdegrunt** [rubyide/vscode-ruby#273]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.4.2
- VS Code version: 1.20.1
- Operating System: macOS
- Hardware (optional): 

I'm using bundler and rbenv.

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
According to #192 rake tasks should be detected.
When I select Taks => Run Task I expect rake tasks to be auto detected, so I can choose tasks like `rake routes`.

### Actual behavior
No tasks are detected.

### Steps to reproduce the problem
Open a rails project.
Select Taks => Run Task

**Comment by connorshea** [comment]
I wonder if this line is the problem:

https://github.com/rubyide/vscode-ruby/blob/2d8e443a33bb56662fe3ad23d2b049b52021acb7/src/task/rake.ts#L91

It runs `rake` without `bundle exec`, which could possibly cause problems?

**Comment by connorshea** [comment]
Alright, I've figured it out!

It's because this [globPattern](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) is busted:

https://github.com/rubyide/vscode-ruby/blob/2d8e443a33bb56662fe3ad23d2b049b52021acb7/src/task/rake.ts#L12

`"**/[rR]akefile{,.rb}"` matches `Rakefile.rb` but not `Rakefile`. Presumably, `{,.rb}` is supposed to match either nothing (hence the comma) or `.rb`. For whatever reason, this doesn't actually work. If you replace `"**/[rR]akefile{,.rb}"` with `"**/[rR]akefile{*,.rb}"` it works perfectly! It detects both files called `Rakefile` and files called `Rakefile.rb`.

I'm not sure if the way globPatterns work was changed in VS Code at some point, or if this has always been broken, but it seems to work after making that change. It has the downside of also catching, e.g. `Rakefile2` or `Rakefilemasdamsmdasdms`, but I can personally live with that.

<img width="1552" alt="Screen Shot 2019-03-15 at 10 02 47 PM" src="https://user-images.githubusercontent.com/2977353/54470533-eaa27200-476e-11e9-9f13-4003993e4807.png">

I'll open a PR.
