### ISSUE TITLE
more suggestions

### ISSUE THREAD

**Issue by gurgeous** [rubyide/vscode-ruby#293]
I may have some time available to work on the extension. Here are some tasks I am interested in tackling. These are not in order. Are any of these of interest? Suggestions welcome:

1. support for rufo formatting, or at least disabling rubocop formatting
1. better user facing error/debug messages for rubocop linting/formatting
1. more updates to the readme (to help people with config issues)
1. add more tests
1. old issue triage

?

**Comment by gurgeous** [comment]
Oh, and perhaps this:

6. enable/run tslint and prettier on our code

**Comment by wingrunr21** [comment]
1. #295
2. Rubocop/linting needs a ton of work in general
3. Yep, thanks for your work starting that out
4. Yep
5. I'm pretty close to just closing all issues except those opened since about last November as the I'm not sure many of them reflect the current state of the project.
6. That is not in this project's scope. Why do the TSLint/ESLint extensions not do that job?

**Comment by gurgeous** [comment]
Oh, for (6) I mean running tslint/prettier on the extension source itself (i.e - `prettier src/ruby.ts`) to catch errors and reformat our code in a standard way. I agree it would be silly to build them into vscode-ruby :) Sorry for the confusion.

**Comment by wingrunr21** [comment]
ohhh, gotcha. Yep, that sounds good to me.

**Comment by gurgeous** [comment]
For (2), see #297

**Comment by gurgeous** [comment]
For (6), see #299. Seems important since one of my PRs already ran into trouble with formatting.

**Comment by gurgeous** [comment]
I'd be happy to help with (5), but I think you'd have to make me an admin. Reading the old issues would also be a good way to start creating a FAQ for the README. Let me know if you want help along those lines.
