### ISSUE TITLE
Intellisense support

### ISSUE THREAD

**Issue by rebornix** [rubyide/vscode-ruby#34]
I'm prototyping with `rsense` but for now it lacks support for Windows platform. Will drop more info here later on.

**Comment by HookyQR** [comment]
@rebornix: I'm writing some code to support the **Go to Definition** functionality, and I'm pretty sure the structures that I'm planning on sending back will provide a substantial amount of what you want for code completion support as well. I'll create a fork for this tonight. Will be using [VM:InstructionSequence](http://ruby-doc.org/core-2.3.1/RubyVM/InstructionSequence.html) in the back end to get the info for an entire workspace. Queries for the info will go to the ruby process rather than trying to create a new parser for Ruby in JavaScript.

I'm fairly sure this will give us nearly everything that is required for the rest of the Extension. (With some hard coded stuff for the StdLib/Core perhaps)

**Comment by cacorka91** [comment]
[license_mkl_1464227767.txt](https://github.com/rubyide/vscode-ruby/files/283329/license_mkl_1464227767.txt)

**Comment by claudiug** [comment]
any news here?

**Comment by HookyQR** [comment]
@claudiug `Go to definition` complete in #59. Requires better parsing of the active file to provide useful code completion.

Used my own ruby parser written in javascript to avoid excessive process spawning.
