### ISSUE TITLE
initialize failed: No prebuilt binaries found

### ISSUE THREAD

**Issue by chenjau** [rubyide/vscode-ruby#415]
### Your environment

- `vscode-ruby` version: v0.21.0
- Ruby version: 2.5.3
- Ruby version manager (if any): rbenv
- VS Code version: 1.31(master)
- Operating System: macos 10.14
- Using language server? yes

when use language server option enabled:
### Expected behavior
it should rebuilding tree-sitter and finish initialization.
### Actual behavior
Server initialization failed

console log:
[Info  - 下午3:31:56] Initializing Ruby language server...
[Info  - 下午3:31:56] Rebuilding tree-sitter for local Electron version
[Error - 下午3:31:59] Server initialization failed.

note: vscode master has been updated to electron 3.

**Comment by wingrunr21** [comment]
Thanks for the report. I depend on the binaries built upstream so I'll file issues there to build against ABI 64.

**Comment by TeeSeal** [comment]
The vscode update reached stable. Same issue there.

**Comment by wingrunr21** [comment]
Yep. I'll cut a release tonight and get tree-sitter upgraded

**Comment by wingrunr21** [comment]
Update:

`tree-sitter-ruby` didn't have a new release cut with the binaries. I've pinged the author to cut a release. Sorry for the inconvenience here. I'll address this ASAP

**Comment by ecbrodie** [comment]
@wingrunr21 Any update on this? I was lucky enough to start working on a Ruby project in VS Code on Feb 7, exactly the day that activity on this Issue picked up again and you said that a release would be cut "tonight"/"ASAP". Any way anyone else can help out with getting a new release cut?

**Comment by wingrunr21** [comment]
I did address it "tonight"/"ASAP". `tree-sitter-ruby` has to have a new release cut so that the binaries can be compiled. As VSCode does not run anything like `npm install`, the only way to get binaries is to pull them from somewhere.

In the mean time, you can downgrade VSCode. I will upgrade this as soon as a release comes out but I'm not the project owner.

**Comment by wingrunr21** [comment]
I just opened an issue there as well to cut a new release

**Comment by wingrunr21** [comment]
Release got cut earlier today so I'll upgrade it here after work today

**Comment by wingrunr21** [comment]
`v0.21.1` should have the updated language server to point at the new binaries. I also pulled in #419 as it made the configuration section title more consistent with other languages.

Sorry for the wait everyone. I'll do better staying on top of this next time

**Comment by pablocrivella** [comment]
Having the same issue here:

### Your environment

vscode-ruby version: v0.24.1
Ruby version: 2.6.3
Ruby version manager: asdf
VS Code version: 1.36.1
Operating System: macos 10.14.5
Using language server? yes

When use language server option enabled:

### Expected behavior

It should rebuilding tree-sitter and finish initialization.

### Actual behavior

```
[Info  - 12:09:02 AM] Initializing Ruby language server...
[Info  - 12:09:02 AM] Rebuilding tree-sitter for local Electron version
[Error - 12:09:02 AM] Server initialization failed.
  Message: Request initialize failed with message: No prebuilt binaries found (target=undefined runtime=undefined arch=undefined libc=undefined platform=undefined)
  Code: -32603 

```

**Comment by wingrunr21** [comment]
#486 is pinned for this
