### ISSUE TITLE
Can't copy values from debug variables

### ISSUE THREAD

**Issue by baelter** [rubyide/vscode-ruby#536]
This seems to have been an issue for other languages as well.
Eg.
https://github.com/Microsoft/vscode/issues/10210
https://github.com/microsoft/vscode-go/issues/1990

Both mention lack of support for support the [evaluateName](https://github.com/Microsoft/vscode/blob/5d645696cc669e4bc9c8824749395c7112e8c845/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1387) property.

**Comment by peret** [comment]
I started looking into this and hope to have a PR ready in a few days.

**Comment by peret** [comment]
One thing I'm not sure about yet is the case where an object's instance variable doesn't have an accessor. Right now, I'm generating an expression like `obj.instance_var` which only works if there's an accessor defined on the object for that variable.
I _could_ use `instance_variable_get` instead, which would always work. However, there's also an "Copy as expression" feature, and these expressions will get long and ugly fast, especially for nested objects.
Unfortunately I also couldn't find a way to detect whether an accessor is defined or not.

Any thoughts?

**Comment by baelter** [comment]
Just scanned the code very briefly and one thing comes to mind. Can you use `this.rubyProcess` and `respond_to?` to generate the code?

**Comment by peret** [comment]
Well, `this.rubyProcess` is meant for communicating with `ruby-debug-ide` specifically, if I understand correctly. I can actually do something similar to what you suggested, by using the `inspect` command of rdebug-ide, instead of `respond_to?`. However, I just realized that this kind of approach will break when there's a method with the same name that isn't a variable accessor. E.g.:
```class SomeClass
  def initialize(value)
    @value = value
  end

  def value
    # some code not being an accessor of @value
    42
  end
end
```
In cases like this, `SomeClass.new.value` would evaluate to something, but it wouldn't be a valid `evaluateName` for the instance variable `@value`.

I think I'm going to change it to use `instance_variable_get`, since that will always do the right thing. It's a pitty that the expression will be so cumbersome, but it's more important to always evaluate the correct thing.
