### ISSUE TITLE
Syntax highlight issue with "=" sign

### ISSUE THREAD

**Issue by vadviktor** [rubyide/vscode-ruby#57]
### Your environment

- `vscode-ruby` version: 	0.5.6
- Ruby version: any
- VS Code version: 1.5.1
- Operating System: Linux

### Expected behavior
No spaces around equal sign should keep correct syntax highlighting for the rest of the code:

![selection_003](https://cloud.githubusercontent.com/assets/238703/18429085/7df1d0a4-78c9-11e6-9c5c-a1dbccbf5385.jpg)

### Actual behavior
When having no spaces around equal sign I see the rest of the highlighting broken:

![selection_002](https://cloud.githubusercontent.com/assets/238703/18429093/92fa67ae-78c9-11e6-89b3-0f4846aebaff.jpg)

### Steps to reproduce the problem

Type in a few lines of code according to the ones seen in above screenshots.

**Comment by HookyQR** [comment]
Turns out `password=` is listed as a **"known function name"**. In my opinion, none of the functions with a trailing `=` should be in this list because they're not called that way, only defined that way. I'll make a PR removing the offending names.

For interest, here are the functions what would result in the same behaviour:

abort_on_exception=, async=, attributes=, avail_out=, charset=, codepage=, comment=, critical=, data=, dataType=, datetime_format=, default=, dn=, egid=, eid=, euid=, extensions=, filter=, fragment=, gid=, groups=, headers=, host=, level=, lineno=, log=, max=, maxgroups=, mtime=, nodeTypedValue=, nodeValue=, ondataavailable=, onreadystatechange=, ontransformnode=, opaque=, orig_name=, params=, password=, path=, pointer=, port=, pos=, preserveWhiteSpace=, priority=, query=, registry=, resolveExternals=, run=, scheme=, scope=, secure=, string=, sync=, text=, to=, typecode=, uid=, url=, user=, userinfo=, validateOnParse=, value=
