### ISSUE TITLE
Wrong colour for "ending" variables

### ISSUE THREAD

**Issue by MicMicMon** [rubyide/vscode-ruby#579]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.6.5
- Ruby version manager (if any): rbenv
- VS Code version: 1.41.1
- Operating System: Linux Fedora
- Using language server? yes

In many places, coloring for the last variable of an expression is malformed. I can't remember all the cases, but I often run into those cases.

For example, with a simple `if` statement and 2 or 3 variables:
![image](https://user-images.githubusercontent.com/37897072/71897040-a77a1b00-3155-11ea-9f38-b01451d8ec8b.png)

Is there something wrong with my theme, or is it an issue with the language server?

**Comment by MicMicMon** [comment]
Other example:

![image](https://user-images.githubusercontent.com/37897072/72349800-7eb9ce80-36dd-11ea-9798-1dc71a88ac4a.png)

But putting `()` shows color ok:

![image](https://user-images.githubusercontent.com/37897072/72349833-8ed1ae00-36dd-11ea-8022-0f75396f449a.png)

Is it an inevitable consequence of Ruby grammar, or can it be fixed?

**Comment by wingrunr21** [comment]
`v0.27.0` will ship with some fixes.

Syntax before:
<img width="448" alt="0 27 0 Syntax Before" src="https://user-images.githubusercontent.com/46283/75123308-7bfab380-5663-11ea-909b-6332c25415a7.png">


Syntax after:
<img width="448" alt="0 27 0 Syntax After" src="https://user-images.githubusercontent.com/46283/75123306-7b621d00-5663-11ea-813e-822e104e60ec.png">

A side effect of this correct is that the `.instance` part of your second example is now correctly identified as a method call instead of a variable.
