### ISSUE TITLE
Using Rubocop with VSCode: reformat lines that are too long

### ISSUE THREAD

**Issue by pitosalas** [rubyide/vscode-ruby#580]
I would like rubcop, invoked from Vscode to reformat lines that are too long.

I've tried Layout/LineLength which reports it as a problem but doesn't reformat.
I've tried Metrics/LineLength and I get an error that this name space is wrong and it should be Layout
I've tried command/shift/p ruby:autocorrect by rubocop and it doesn't fix the line
I've tried command/shift/p ruby:lint by rubocop and it doesn't fix the line

In the "problems" I get "Line too Long [87/8-. (convention:Layout/LineLength) for each line that is too long.

I have the latest version of the rubpocop gem, and vscode. I am running the ruby, ruby-robocop vscode extensions.

**Comment by mmzoo** [comment]
Hi Pito. To begin with, let me state that this is unlikely an issue with this extension, but rather a configuration problem on your side. But I thought maybe I can help anyway - I don't see any other forum where you could have asked your question, either 😄 

> I've tried Metrics/LineLength and I get an error that this name space is wrong and it should be Layout

This is expected. LineLength was part of "Metrics" before, but now it resides in the "Layout" namespace.

> I've tried Layout/LineLength which reports it as a problem but doesn't reformat.

Rubocop has two functionalities. Linting and autocorrecting. The former tells you what is wrong and the latter attempts to fix problems (to the degree that they are fixable by a machine rather than a human). We need to treat these two things separately.

If you run `rubocop myfile.rb` it will show you problems. If you run `rubocop -a myfile.rb` it will attempt to fix the problems. VSCode essentially runs these commands under the hood. One thing for you to try is to run these commands yourself manually and see that they do what they should.

> I've tried command/shift/p ruby:autocorrect by rubocop and it doesn't fix the line
> I've tried command/shift/p ruby:lint by rubocop and it doesn't fix the line

I may be mistaken, but I believe these are provided by the `ruby-robocop` extension which has some overlapping functionality with this extension here called `ruby`. One thing you could try is to remove the `ruby-robocop` and only rely on the built-in features by the `ruby` extension. This will make debugging easier and helps narrow down the issue.

By the way: 

* What operating system are you using?
* Do you use rbenv or RVM to manage ruby?

Also, let us double-check your settings. This is what I have:

![Screen Shot 2020-01-17 at 14 53 51](https://user-images.githubusercontent.com/1029840/72617439-3991d880-3939-11ea-950b-d185842df7dd.jpg)

Notice the link "Edit in settings.json" in the very bottom of my screenshot. You will have to click on that, since the last setting cannot be added just by clicking. You'll have to add a `ruby.lint` section to your settings file as below:

The settings from the screenshot above translate directly into this settings.json file:

```json
{
  "ruby.codeCompletion": "rcodetools",
  "ruby.format": "rubocop",
  "ruby.intellisense": "rubyLocate",
  "ruby.interpreter.commandPath": "~/.rbenv/shims/ruby",
  "ruby.lint": {
    "rubocop": true
  },
  "ruby.useLanguageServer": true
}
```

Then, when I run "Format Document", rubocop autocorrects my files.

![Screen Shot 2020-01-17 at 15 00 39](https://user-images.githubusercontent.com/1029840/72617877-3ba86700-393a-11ea-8cdb-ba21d8febb5d.jpg)

I recommend that this issue be closed, because, as I mentioned in the beginning, this is more a user setting problem, rather than an actual but in the software. And I could not see where questions like these should be asked either. Usually there is a gitter.im chat or a mailing list or some community-forum where these questions can be asked without interrupting the developer workflow. stackoverflow.com is also a good place to ask questions.

Good luck!

**Comment by pitosalas** [comment]
Hi Mmzoo (?)

First of all thanks for your generous response. I agree that it's likely a config problem. But there are many traps for a user when trying to assess the configuration. There are many overlapping extensions, some that depend on each other, some that are just different but similar. It's never clear which one might be required or conflicting. See  below.

> I've tried Metrics/LineLength and I get an error that this name space is wrong and it should be Layout

I posted a question on the Rubocop issues where I was told to use Metrics by "someone." (https://github.com/rubocop-hq/rubocop/issues/7613) So who should I believe? I will believe you!
> 
> This is expected. LineLength was part of "Metrics" before, but now it resides in the "Layout" namespace.
> 
> I've tried Layout/LineLength which reports it as a problem but doesn't reformat.
> 
> Rubocop has two functionalities. Linting and autocorrecting. The former tells you what is wrong and the latter attempts to fix problems (to the degree that they are fixable by a machine rather than a human). We need to treat these two things separately.

Ok...

> 
> If you run rubocop myfile.rb it will show you problems. If you run rubocop -a myfile.rb it will attempt to fix the problems. VSCode essentially runs these commands under the hood. One thing for you to try is to run these commands yourself manually and see that they do what they should.

Yes they do. But I have a hash literal that spans three lines that it reports as too long but doesn't fix. Is it supposed to?

`a = {a: 100, b: 200, c: 300, a1: 100, b1: 200, c1: 300, a2: 100, b2: 200, c2: 300, a3: 100, b3: 200, c3: 300, a4: 100, b4: 200, c4: 300, a5: 100, b5: 200, c5: 300, a6: 100, b6: 200, c6: 300, a7: 100, b7: 200, c7: 300}`

`Layout/LineLength:
  Max: 80
  Enabled: true`

> I've tried command/shift/p ruby:autocorrect by rubocop and it doesn't fix the line
> I've tried command/shift/p ruby:lint by rubocop and it doesn't fix the line
> 
> I may be mistaken, but I believe these are provided by the ruby-robocop extension which has some overlapping functionality with this extension here called ruby. One thing you could try is to remove the ruby-robocop and only rely on the built-in features by the ruby extension. This will make debugging easier and helps narrow down the issue.

You're right. I had both installed. I've removed ruby-rubocop.
> 
> By the way:
> 
> 	• What operating system are you using? MacOS (latest)
> 	• Do you use rbenv or RVM to manage ruby? (rbenv)

I use Rbenv. I see that I have to manually tell vscode:   "ruby.interpreter.commandPath": "~/.rbenv/shims/ruby",

Do I also have to do that for rubcop?

Here are my settings:

{
    "workbench.startupEditor": "newUntitledFile",
    "editor.minimap.enabled": false,
    "extensions.ignoreRecommendations": true,
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "sync.gist": "23c3df27305ae4d93c4493340b8d39fb",
    "workbench.colorTheme": "Visual Studio Light",
    "window.zoomLevel": 0,
    "explorer.confirmDragAndDrop": false,
    "editor.wordWrap": "bounded",
    "editor.wordWrapColumn": 100,
    "files.associations": {
        "*.erb": "markdown"
    },
    "git.postCommitCommand": "push",
    "ruby.intellisense": "rubyLocate",
    "ruby.useLanguageServer": true,
    "code-runner.clearPreviousOutput": true,
    "ruby.format": "rubocop",
    "ruby.codeCompletion": "rcodetools",
    "ruby.interpreter.commandPath": "~/.rbenv/shims/ruby",
    "ruby.lint": {
        "rubocop": true
    }
}

(Note that I had Solargraph but deleted it also to continue testing.)

But there's still a config problem (yes, I have done rbenv rehash)

Format: executing rubocop -s /Users/pitosalas/mydev/cosi105b/content/content/topics/scripts/elevator.rb -a...
[Error - 9:58:01 AM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: 
    unable to execute rubocop -s /Users/pitosalas/mydev/cosi105b/content/content/topics/scripts/elevator.rb -a:
    Error: spawn rubocop ENOENT - command not found
  Code: -32603 

Also in the right click menu I see both "Format Document" and "Format Document With..." which implies that Vscode or something still thinks there are two formatters registered. The only extensions I have enabled are: Ruby 0.26.0, VsCode Ruby 0.26.0 and Settings Sync 3.4.3

Again thanks a lot!

Pito

**Comment by mmzoo** [comment]
> So who should I believe?

In case of doubt [go to the source](https://github.com/rubocop-hq/rubocop/blob/8246647a052aa922b0a40c78e7ff646f6fc657d1/lib/rubocop/cop/layout/line_length.rb#L7). `LineLength` is a `Layout` cop, not a `Metric` cop.

> But I have a hash literal that spans three lines that it reports as too long but doesn't fix. Is it supposed to?

I did not know that rubocop can fix line length issues, but [the documentation](https://github.com/rubocop-hq/rubocop/blob/8246647a052aa922b0a40c78e7ff646f6fc657d1/lib/rubocop/cop/layout/line_length.rb#L14-L18) says that hashes are supported by auto-fix.

You can test this by running this manually in a terminal:

```bash
rubocop --auto-correct ~/mydev/cosi105b/content/content/topics/scripts/elevator.rb
```

If that does not fix it, vscode cannot either (because vscode just runs that command)

> Error: spawn rubocop ENOENT - command not found

This indicates that vscode cannot find your rubocop executable.

When you type `which rubocop`, where does it say your executable is located? Is it part of a `Gemfile` or have you installed it globally with just `gem install rubocop`?

What strikes me as unusual is that vscode can run the rubocop linter (because you see the error highlighted) but not autocorrect (the spawning error you get). That's really weird.

**Comment by pitosalas** [comment]
Hi!

> In case of doubt go to the source. LineLength is a Layout cop, not a Metric cop.

touché

> 
> But I have a hash literal that spans three lines that it reports as too long but doesn't fix. Is it supposed to?
> 
> I did not know that rubocop can fix line length issues, but the documentation says that hashes are supported by auto-fix.
> 
> You can test this by running this manually in a terminal:
> 
> rubocop --auto-correct ~/mydev/cosi105b/content/content/topics/scripts/elevator.rb
> If that does not fix it, vscode cannot either (because vscode just runs that command)

Indeed it does not fix it! I thought it would.

> 
> Error: spawn rubocop ENOENT - command not found
> 
> This indicates that vscode cannot find your rubocop executable.
> 
> When you type which rubocop, where does it say your executable is located? Is it part of a Gemfile or have you installed it globally with just gem install rubocop?

/Users/pitosalas/.rbenv/shims/rubocop

> 
> What strikes me as unusual is that vscode can run the rubocop linter (because you see the error highlighted) but not autocorrect (the spawning error you get). That's really weird

I know. It's not that I really need it to reformat hash lines that are too long. But I want to have a valid config so I dont chase my tail on other things. 

At this point all I have are these three extensions: 

VSCode Ruby 0.26.0
Ruby 0.26.0
Settings Sync 3.4.3

Why two Ruby extensions? If I uninstall Ruby  then if I ask to format a source file it says "no formater". If I try to uninstall the Vscode Ruby extension I get an error that the Ruby extension needs it. My point is that my install is really minimalist. Below is my whole settings.json:

{
    "workbench.startupEditor": "newUntitledFile",
    "editor.minimap.enabled": false,
    "extensions.ignoreRecommendations": true,
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "sync.gist": "23c3df27305ae4d93c4493340b8d39fb",
    "workbench.colorTheme": "Visual Studio Light",
    "window.zoomLevel": 0,
    "explorer.confirmDragAndDrop": false,
    "editor.wordWrap": "bounded",
    "editor.wordWrapColumn": 100,
    "files.associations": {
        "*.erb": "markdown"
    },
    "git.postCommitCommand": "push",
    "ruby.intellisense": "rubyLocate",
    "ruby.useLanguageServer": true,
    "code-runner.clearPreviousOutput": true,
    "ruby.format": "rubocop",
    "ruby.codeCompletion": "rcodetools",
    "ruby.interpreter.commandPath": "~/.rbenv/shims/ruby",
    "ruby.lint": {
        "rubocop": true
    }
}

If I ask to format the document (elevator.rb) I get:

[Info  - 12:04:53 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/pitosalas/mydev/dotfiles/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm
Lint: executing rubocop -s /Users/pitosalas/mydev/cg-topics/scripts/elevator.rb -f json...
Lint: unable to execute rubocop -s /Users/pitosalas/mydev/cg-topics/scripts/elevator.rb -f json as the command could not be found
Format: executing rubocop -s /Users/pitosalas/mydev/cg-topics/scripts/elevator.rb -a...
[Error - 12:07:38 PM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: 
    unable to execute rubocop -s /Users/pitosalas/mydev/cg-topics/scripts/elevator.rb -a:
    Error: spawn rubocop ENOENT - command not found
  Code: -32603 


Any clue at all? 

Pito

**Comment by mmzoo** [comment]
> Why two Ruby extensions?

Now that is a good question! I'm new to vscode as well and all I can gather is that "VSCode Ruby" only slightly improves things (syntax highlighting and debugging) according to the [README](https://github.com/rubyide/vscode-ruby/blob/dcfbb8458dde78d452d8d910fdff4247bcd4f1cf/packages/vscode-ruby/README.md#using-with-the-ruby-extension):

>  It is meant to be used alongside the Ruby extension. [...] This extension is listed as a dependency for the Ruby extension and does not need to be installed independently

> spawn rubocop ENOENT - command not found

Now, this is a shot in the dark, but if I read [this code](https://github.com/rubyide/vscode-ruby/blob/dcfbb8458dde78d452d8d910fdff4247bcd4f1cf/packages/vscode-ruby-client/src/format/RuboCop.ts#L26-L37) correctly, you should be able to specify the path like so:

```json
{ 
  "ruby.lint": {
    "rubocop": {
      "exe": "~/.rbenv/shims/rubocop"
    }
  }
}
```

For what it's worth you might try to temporarily disable the `ruby.useLanguageServer`, I don't know the effects of that option.

My suspicion is that linting a file and formatting a file goes two separate code paths, so one succeeds for you and one does not.

You could also try to create a single ruby file somewhere in `/tmp/sometest.rb` and only open that file and see if you can lint and format. That way we can exclude inconsistencies with bundler.

**Comment by pitosalas** [comment]
Thanks... One more odd datapoint.

Lint: unable to execute ~/.rbenv/shims/rubocop -s /Users/pitosalas/mydev/deleteme1/foo.rb -f json -l as the command could not be found
Format: executing rubocop -s /Users/pitosalas/mydev/deleteme1/foo.rb -a...
[Error - 7:53:41 AM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: 
    unable to execute rubocop -s /Users/pitosalas/mydev/deleteme1/foo.rb -a:
    Error: spawn rubocop ENOENT - command not found
  Code: -32603 

If you look closely it is calling rubocop -s  which means take input from stdin. If I type that command into the shell it just sits there waiting for input. I don't know why.

I wonder if the vscode-rubocop extension is still needed...

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by wingrunr21** [comment]
@pitosalas There is specific documentation on troubleshooting this and why there's a `-s` in the command. Please review the [troubleshooting docs](https://github.com/rubyide/vscode-ruby/blob/master/docs/troubleshooting.md#linting-or-formatting-is-incorrect).

**Comment by eduAndros** [comment]
@pitosalas is this solved?

**Comment by pitosalas** [comment]
Yes, Thanks.
Pito Salas
Faculty, Computer Science
Brandeis University

**Comment by eduAndros** [comment]
> Yes, Thanks. Pito Salas Faculty, Computer Science Brandeis University
> […](#)
> On Apr 9, 2021, at 10:19 AM, eduAndros ***@***.***> wrote: @pitosalas is this solved? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

How did you get it working?
