### ISSUE TITLE
Intellisense with LanguageServer: Is it really still rubyLocate? Solargraph?

### ISSUE THREAD

**Issue by ecbrodie** [rubyide/vscode-ruby#599]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.5
- Ruby version manager (if any): rvm
- VS Code version: 1.43.2
- Operating System: MacOS 10.15.3
- Using language server? (eg `useLanguageServer` is true in your configuration?) true

This isn't really a bug, more of a question. It isn't fully clear to me, based on the documentation, what the official configuration is for Intellisense with the language server enabled. Is it still this?

```
"ruby.intellisense": "rubyLocate"
```

I was confused by error messages I got from the extension in my IDE, telling me that the `ruby.intellisense` configuration is required, even though this option is only listed in the _Legacy Configuration_ page. It made me think that the Language Server had its own separate intellisense built-in. When I configured this option on my IDE anyway, Intellisense started to work fine.

For example, without `ruby.intellisense` set, CMD-click on class names would not jump to the class's file. But with "rubyLocate" set, it worked.

I also found it to be entirely plausible, based on the Language Server documentation, that Intellisense is supposed to be provided by the Solargraph extension.

This isn't a complaint, really just a question. I'm happy to help chip in with documentation updates as needed, to better illustrate how Intellisense works with the language server enabled.

**Comment by atipugin** [comment]
Same here. `useLanguageServer` flag doesn't do anything useful. Go To Definition still requires `ruby.intellisense` set to `rubyLocate`.

**Comment by wingrunr21** [comment]
@atipugin other than all the other must have features other users requested. I look forward to your PR to add something useful

@ecbrodie The server today only exposes basic intellisense. It’s been a todo item for awhile

**Comment by atipugin** [comment]
@wingrunr21 hey, no offense meant. Just wanted to know if any additional configuration required for LPS, because docs aren't really clear about it for now

**Comment by wingrunr21** [comment]
The docs are up to date as far as support. If they can be clearer, a PR would be great. I've been trying to improve documentation as gaps come along so will happily take submissinos.

`rubyLocate` is the best built-in method right now. Otherwise, Solargraph is a really awesome project.

I've been architecting how to add better support for a bit now. One problem I haven't yet solved is YARD documentation. I'd like to make Intellisense as out of the box (eg useful 😉) as possible. One thing the linter/formatter settings have reinforced is that everyone's Ruby setups are so varied it is hard to ensure you can call out to an external program. I also can't read an existing YARD cache as it is a collection of serialized Ruby objects. I've got a few ideas (including only supporting basic YARD intellisense via the syntax tree unless I can call out to yard itself) but open to any others.
