### ISSUE TITLE
Formatters adding extra newlines on windows if VC Code eol setting is LF insteads of CRLF

### ISSUE THREAD

**Issue by nipinium** [rubyide/vscode-ruby#665]
### My environment

- `vscode-ruby` version: v0.27.0
- Ruby version: 2.7.2p137
- Ruby version manager (if any): none
- VS Code version: 1.50.0
- Operating System: Windows 10
- Using language server? Yes

### Expected behavior
The formatters work correctly.

### Actual behavior
The formatters keep inserting extra newlines if the default end of line character is LF (`\n`) insteads of CRLF (`\r\n`). I tried ruby, rubyfmt and standardrb, all behaved the same.

Before formatting:
![before](https://user-images.githubusercontent.com/34429224/95766946-37995200-0cde-11eb-80d3-935dd1254f9e.png)

After formatting:
![after](https://user-images.githubusercontent.com/34429224/95766970-408a2380-0cde-11eb-8fae-4cc4ea7066d2.png)

**Comment by cscorley** [comment]
I also observe this issue, but with `"files.eol": "auto"`.  However, with auto set, it is using CRLF for .rb files (indicated in status bar) and changing them (via status bar) to LF also causes this behavior.

Some other observations:

1. Running rubocop from Terminal (pwsh) does not do this: `rubocop -a`
2. Subsequent saves with auto (CRLF), which re-run rubocop from the plugin, will actually revert the line changes on every other save for some files.  So, every save either introduces more new lines or removes them.

**Comment by cscorley** [comment]
This looks related to #644.  

The solution suggested there is to use cmd instead of powershell.  However, switching to `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"` and `"terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\cmd.exe",` does not fix this.  Using defaults for those settings also does not work, since the default for VS Code is PowerShell now.

**Comment by nipinium** [comment]
I'm using `cmd.exe` by default. Confirmed that it does not resolve the issue.

**Comment by cscorley** [comment]
Me too.  I've tried it several different ways, and observe the same behavior no matter what terminal type I am using and even when using different formatters.  I am thinking it might be either how the edits are actually applied or the diffing engine is not compatible with CLRF line endings.

For the first thought, I think that this form of transformation in the BaseFormatter may be outdated:

https://github.com/rubyide/vscode-ruby/blob/e2f901cad299beec3134446605a3dff094545353/packages/language-server-ruby/src/formatters/BaseFormatter.ts#L103-L110

There are several static methods on the `TextEdit` that can be used instead: https://code.visualstudio.com/api/references/vscode-api#TextEdit

The current approach may be an equivalent application as using the static methods in the end, but I figured it was worth a shot.  I attempted to get a development environment bootstrapped in order to test my changes, but haven't been able to get a working environment going locally yet.  I kind of gave up this weekend trying, so I didn't get to look into the diffing engine either.

**Comment by cscorley** [comment]
Hello @nipinium 

I was able to actually get the developer environment working locally with this and was able to debug what /my/ problem at least was, and likely yours as well.  TL;DR:  My suggestion is to disable the [Layout/EndOfLine](https://docs.rubocop.org/rubocop/1.0/cops_layout.html#layoutendofline) rule in your project configuration if using Rubocop (or the equivalent for your preferred formatter), or set it specifically to use LF-only if that is your desired output.

The first is that the files I was trying to format were generated by Rails, and rails defaulted to LF line endings (as opposed to CRLF).  VS Code in auto mode allows me to edit these LF files just fine, and then on save the formatter would run them though rubocop.  Rubocop then gets a file with all LFs and, by default on Windows, replaces them all with CRLF since Rubocop uses `native` mode by default for `Layout/EndOfLine`.  These CRLFs are correctly reloaded back into VS Code and this extension applies the differences appropriately.  

However, this is where it goes sideways.  VS Code still represents the file as LF, and thus, as it's being saved, all the changes the extension applied converts all CRs to LFs, producing additional lines.  _I don't think this is necessarily a bug in the extension_, as much as I think special care needs to be applied depending on the mode of the file VS Code is currently running.  Saving the file twice appears to maybe do nothing, but all of the extra line endings are being deleted by Rubocop, while also replacing every LF with CRLF that VS Code in turn replaces with LFLF (I think?).  Quite annoying.

I'm not familiar enough with VS Code extension ecosystem to know what an appropriate fix is for this just yet.  Hope to explore further soon 😄

**Comment by cscorley** [comment]
I'm now currently wondering if rubocop has buggy output on CRLF input from stdin/stdout streams on Windows (or even something with how those streams are handled in Ruby itself -- I am not sure)

Here is the exact output the RuboCop formatter is running on, captured in VSCode, and it looks mostly normal, except for the end, after the formatted file output delimiter:

`Inspecting 1 file\r\nC\r\n\r\nOffenses:\r\n\r\n'c:/Users/cscorley/git/blog/crlf.rb':1:1: C: Style/Documentation: Missing top-level class documentation comment.\r\nclass WelcomeController < ApplicationController\r\n^^^^^\r\n'c:/Users/cscorley/git/blog/crlf.rb':1:1: C: Style/FrozenStringLiteralComment: Missing frozen string literal comment.\r\nclass WelcomeController < ApplicationController\r\n^\r\n\r\n1 file inspected, 2 offenses detected, 1 more offense can be corrected with `rubocop -A`\r\n====================\r\nclass WelcomeController < ApplicationController\r\r\n  def index; end\r\r\nend\r\r\n`

Original text:
`'class WelcomeController < ApplicationController\r\n  def index; end\r\nend\r\n'`

Indeed, trying this directly in pwsh 7 produces the same report, with the line endings as '\r\r\n' instead of simply '\r\n'.

**Comment by cscorley** [comment]
With some more experimentation, here is a full mapping of what occurs for each formatter via the extension:

- File input: LF
    - Rubocop output: CRLF
    - Rufo output: CRLF
    - Rubyfmt output: CRLF
    - Standard output: CRLF
- File input: CRLF
    - Rubocop output: **CRCRLF**
    - Rufo output: CRLF
    - Rubyfmt output: CRLF
    - Standard output: **CRCRLF**

It seems that only Rubocop and Standard output the double CR on CRLF input.  Since every single one of these outputs CRLF on LF input, this means that every formatter will appear to duplicate lines in VS Code, as it will shove all the CRs into LFs in order to fit the existing document format of LF.  Ideally, to me, the extension would detect this and either:

a) swap the document from LF to CRLF before handing off the TextEdits
b) perform an additional pass to convert the formatter output into the original documents line endings

I have experimented with b) and it seems to work quite well for me (same environment as the OP).  The problem is handling CRCRLF outputs cleanly.  I wrote some string replacement code to do this, and this also seems to be working for me in general.  I can open a PR for this change, but I really don't like it and don't yet know enough to reliably implement a), which I think would be better since it both preserves the correctly formatted document and respects what the formatter actually outputs (a line conversion).

**Comment by cscorley** [comment]
Ended up opening a bug for this on Rubocop:  https://github.com/rubocop-hq/rubocop/issues/9109

Perhaps someone there can explain more
