### ISSUE TITLE
Replacement for 'legacy' `ruby -wc` lint ?

### ISSUE THREAD

**Issue by andyw8** [rubyide/vscode-ruby#725]
Hi,

https://github.com/rubyide/vscode-ruby/blob/master/docs/legacy.md lists `ruby -wc` as a 'legacy' linting option and it seems this doesn't seem to work any more – is there a modern way to do this? I don't see anything on https://github.com/rubyide/vscode-ruby/blob/master/docs/linting.md

**Comment by wingrunr21** [comment]
It's `legacy` because it had low usage and was not moved over to the language server. If a PR is opened to add support to the language server, I'm happy to add support back in.

In terms of a modern way of doing it: `rubocop` should have the same capabilities. I realize that requires installing a gem so it isn't quite the same.

**Comment by andyw8** [comment]
Thanks for the information. I understand that the `Lint/Syntax` cop should be an effective replacement.
